### PR TITLE
Refant selection improvements

### PR DESCRIPTION
**Pull request by radonnachie**

### CODE REVIEW

**Comment by talonmyburgh** [comment]
Is there an instance where the prior code was not working or is this predominantly about neatening and legibility?

**Comment by talonmyburgh** [comment]
As far as I can tell, it did not do anything incorrect, only, the antenna that were reported to be in the observation were in fact not?
Now we just check that the antenna is present in:
```
 observed_antenna_names = [
            self.metadata['ant_names'][self.metadata['ant_numbers'].index(antnum)]
            for antnum in self.metadata['ant_numbers_data']
        ]
```
instead of:
```
self.metadata['ant_curr']
```
where 'ant_curr' is renamed to 'ant_numbers_data'?

**Comment by radonnachie** [comment]
I don't think you're reading the change correctly:

- No relying on an antenna's number being the last 2 characters of its name
- In lieu of displacement info for prioritisation of antenna, iterate through those that were a part of the observation (instead of falling back to a hardcoded antenna)
- Raise an error if none of the above works instead of falling back to a hardcoded reference antenna name
- and yes, better name for the `ant_curr` key-value

**Comment by talonmyburgh** [comment]
Gotcha, seems a bit neater and no harm done 👍

**Pull request merged**
